#input("first number: ")
#input("second number: ")
#my_first_number = ("first number")
#my_second_number = ("second number")
#print(my_first_number + my_second_number)
no1 = int(input("first number: "))
no2 = int(input("second number: "))
no3 = int(input("third number"))
print("the sum of {}, {} and {} is {} ". format(no1, no2, no3, no1 + no2 + no3 ))
sum = (no1 + no2 + no3)
print("{} divided by {} is {} ". format(sum, no3, sum / no3))